export const navigateSafely = async (navigate, path) => {
    try {
      await navigate(path);
    } catch (error) {
      console.error('Error en la navegaci√≥n:', error);
      throw error;
    }
  };